### ISSUE TITLE
where is onnxruntime-1.2.0-all.jar

### ISSUE THREAD

**Issue by Jie-Yuan** [amesar/mlflow-examples#1]
<dependency>
      <groupId>ai.onnxruntime</groupId>
      <artifactId>ai.onnxruntime</artifactId>
      <version>1.2.0</version>
      <scope>system</scope>
      <systemPath>CHANGE_ME/onnxruntime-1.2.0-all.jar</systemPath>
    </dependency>

**Comment by amesar** [comment]
Its not yet published in maven central so you have build it yourself from https://github.com/microsoft/onnxruntime.

See: https://github.com/amesar/mlflow-examples/tree/master/scala/onnx#build-onnx-runtime-jar
