### ISSUE TITLE
how to serve the tf keras model at local

### ISSUE THREAD

**Issue by Foina** [amesar/mlflow-examples#3]
I saw your example use docker to serving the tf kears model, may I ask do you know how to serve it at local?
Cause I feel TensorFlow different from sklearn or xgboost. It seems we use the tf to save the model as .pb

**Comment by amesar** [comment]
To serve the TF model locally see: [Keras Local Web server](https://github.com/amesar/mlflow-examples/tree/master/python/keras_tf_mnist#1-local-web-server)
